// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91WFNXcT55tA2NQftYTscpD1C0s74aVo',
    appId: '1:1034472593863:web:12903f36ff0f2c9effe1e2',
    messagingSenderId: '1034472593863',
    projectId: 'data-persistence-4ea67',
    authDomain: 'data-persistence-4ea67.firebaseapp.com',
    storageBucket: 'data-persistence-4ea67.appspot.com',
    measurementId: 'G-WE19E9S6TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSirB7OzER7A_rXJeAv_dZfRP7bXoh11g',
    appId: '1:1034472593863:android:e0661413469c213fffe1e2',
    messagingSenderId: '1034472593863',
    projectId: 'data-persistence-4ea67',
    storageBucket: 'data-persistence-4ea67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZOZsofjr92Rq5XlDsIBODPSt7SUhXQU',
    appId: '1:1034472593863:ios:33ed65e9910752a1ffe1e2',
    messagingSenderId: '1034472593863',
    projectId: 'data-persistence-4ea67',
    storageBucket: 'data-persistence-4ea67.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZOZsofjr92Rq5XlDsIBODPSt7SUhXQU',
    appId: '1:1034472593863:ios:33ed65e9910752a1ffe1e2',
    messagingSenderId: '1034472593863',
    projectId: 'data-persistence-4ea67',
    storageBucket: 'data-persistence-4ea67.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91WFNXcT55tA2NQftYTscpD1C0s74aVo',
    appId: '1:1034472593863:web:047b63767bf1fc8cffe1e2',
    messagingSenderId: '1034472593863',
    projectId: 'data-persistence-4ea67',
    authDomain: 'data-persistence-4ea67.firebaseapp.com',
    storageBucket: 'data-persistence-4ea67.appspot.com',
    measurementId: 'G-V83DQGS2KC',
  );
}
